# fly.toml app configuration file generated for go-days on 2025-08-10T19:21:23-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'go-days'
primary_region = 'ewr'

[build]
[build.args]
GO_VERSION = '1.24.5'

[http_service]
auto_start_machines = true
auto_stop_machines = false
force_https = true
internal_port = 8081
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
